- packages/widget/src/AppProvider.tsx
- packages/widget/src/i18n/index.ts
- packages/widget/src/index.ts
If the project using this widget is also using i18next (like us), current code will initialize user's i18next twice. This PR creates a new instance that is provided through react provider, so it won't have side-effect on user's i18next instance.
Let users pass their own i18next instance or an option to overwrite current translation files.
> fix: isolate i18next instance

- packages/wallet-management/src/types/index.ts
- packages/wallet-management/src/walletIcons/index.ts
- packages/wallet-management/src/wallets.ts
Ticket: https://lifi.atlassian.net/browse/LF-4489
✅ `yarn build` ran through
> fix: remove Huobi, MeetOne, AToken and MyKey wallets (LF-4489)

- packages/widget/src/components/GasMessage/GasMessage.tsx
- packages/widget/src/hooks/useGasSufficiency.ts
- packages/widget/src/pages/TransactionPage/StartTransactionButton.tsx
For Stargate and Connext, the gas is to be paid from the SAFE account rather than the EOA or it being deducted from the amount being funds being bridged/swapped
> fix: enable gas sufficiency check for SAFE

- packages/widget-playground/src/config.ts
- packages/widget/src/AppRoutes.tsx
- packages/widget/src/components/Header/NavigationHeader.tsx
- packages/widget/src/components/SendToWallet/SendToWalletButton.tsx
- packages/widget/src/components/Step/Step.tsx
- packages/widget/src/hooks/useToAddressReset.ts
- packages/widget/src/pages/SendToWallet/ConfirmAddressSheet.tsx
- packages/widget/src/pages/SendToWallet/SendToConfiguredWalletPage.tsx
- packages/widget/src/pages/SendToWallet/index.ts
- packages/widget/src/pages/TransactionDetailsPage/TransactionDetailsPage.tsx
- packages/widget/src/providers/WidgetProvider/WidgetProvider.tsx
- packages/widget/src/providers/WidgetProvider/utils.ts
- packages/widget/src/stores/bookmarks/BookmarkStore.tsx
- packages/widget/src/stores/bookmarks/createBookmarkStore.ts
- packages/widget/src/stores/bookmarks/types.ts
- packages/widget/src/stores/form/FormStore.tsx
- packages/widget/src/stores/routes/utils.ts
- packages/widget/src/types/widget.ts
- packages/widget/src/utils/navigationRoutes.ts
Jira: [LF-5324](https://lifi.atlassian.net/browse/LF-5324)
Introducing the Curated Wallets section that as a follow on to the bookmarked send to wallets work
This heavy relies on changes to the widget config. You should see the entries below commented out in the widget-playground
```
toAddress: {
name: 'Jenny',
address: '0xAB3Afc314e75dC1648A2E31c06861A07a048C050',
chainType: ChainType.EVM,
},
toAddresses: [
{
name: 'Lenny',
address: '0x552008c0f6870c2f77e5cC1d2eb9bdff03e30Ea9',
chainType: ChainType.EVM,
},
{
address: '0x552008c0f6870c2f77e5cC1d2eb9bdff03e30Ea0',
chainType: ChainType.EVM,
},
{
name: 'Sol',
address: '6AUWsSCRFSCbrHKH9s84wfzJXtD6mNzAHs11x6pGEcmJ',
chainType: ChainType.SVM,
},
],
```
`toAddress` and `toAddresses` work independently of each other 
- adding `toAddresses` will …
> feat: curated wallets for the destination address selection

- packages/widget/src/hooks/useRoutes.ts
- packages/widget/src/hooks/useSettingMonitor.ts
- packages/widget/src/pages/SelectEnabledToolsPage/SelectEnabledToolsPage.tsx
- packages/widget/src/pages/SettingsPage/BridgeAndExchangeSettings.tsx
- packages/widget/src/stores/settings/types.ts
- packages/widget/src/stores/settings/useSettingsStore.ts
We would like to send only modified bridges/exchanges to the backend, so we need to switch from sending all of them in allow property to using deny property and sending only disabled ones.
- Enable/disable bridges/exchanges and try to get a route
- Check what we send to the backend
- Check what we store in localStorage and whether those values are correctly hydrated after page refresh
> refactor: send only modified tools to backend and simplify tools handling

- packages/widget/src/components/Routes/RoutesExpanded.tsx
It also improves exit animation by caching routes locally using refs. Part of #185 for v3.
https://github.com/lifinance/widget/assets/18644653/2bf39968-f7f8-4085-b70e-d3701babf5d2
https://github.com/lifinance/widget/assets/18644653/2653892f-a2b2-447b-bc07-f2563d735190
> fix: expandable variant is not shown with a deep route tree

- packages/widget/src/components/SendToWallet/SendToWalletButton.tsx
1. Go to Jumper staging env 
2. Connect your MetaMask
3. Select your wallet as the destination wallet from `Connected wallets` in the bookmarks
4. Refresh the page
5. Selected bookmark should restore the name from connected wallets, but it doesn't
This PR fixes this 🙂
> fix: restore bookmark name from connected wallet

- packages/widget-playground/src/store/editTools/createEditToolsStore.ts
Requested by Vilen
https://discord.com/channels/849912621360218112/1209523710558732358/1209532051888541716
When a user first lands on the playground the tool draw will be open
> feat: start with playground tool drawer open

- packages/widget-playground/src/components/DrawerControls/DrawerControls.style.tsx
- packages/widget-playground/src/components/DrawerControls/DrawerControls.tsx
- packages/widget-playground/src/components/DrawerControls/DrawerHandle.tsx
- packages/widget-playground/src/store/editTools/createEditToolsStore.ts
This PR is to ensure that the config section of the code section returns to the default size when a user navigates to other sections of the playground.
I've also added in an visual indicator to emphasize that the config section can be resized.
> feat: changes to code section resizing

- packages/widget/src/pages/TransactionPage/StatusBottomSheet.style.tsx
- packages/widget/src/pages/TransactionPage/StatusBottomSheet.tsx
Jira: [LF-7863](https://lifi.atlassian.net/browse/LF-7863)
Added skeleton to allow for a delay in the Swap success message display on the StatusBottomSheet
https://github.com/lifinance/widget/assets/7836726/88a6f624-b6e9-4428-ab74-6951197cdb6e
https://github.com/lifinance/widget/assets/7836726/3d49af62-519e-4c51-b2d3-dd10c69c6119
[LF-7863]: https://lifi.atlassian.net/browse/LF-7863?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add skeleton for swap success message

- .eslintrc
- package.json
- packages/widget-playground-next/package.json
- packages/widget-playground/package.json
- packages/widget/src/pages/RoutesPage/RoutesPage.tsx
- yarn.lock
Jira: [LF-7885](https://lifi.atlassian.net/browse/LF-7885)
We will need to do a bit more work in the repo before we can take eslint v9
This PR drops us back to using v8.57 for now.
[LF-7885]: https://lifi.atlassian.net/browse/LF-7885?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: rollback to previous version of eslint

- packages/wallet-management/package.json
- packages/widget/package.json
Jira: [LF-8183](https://lifi.atlassian.net/browse/LF-8183)
I've updated the peer dependencies in Widget here - there is a caveat to using this when using yarn link. See details on the ticket
[LF-8183]: https://lifi.atlassian.net/browse/LF-8183?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: improve dep management

- examples/nextjs/app/components/ClientOnly.tsx
- examples/nextjs/app/components/Widget.tsx
- examples/nextjs/app/hooks/useHydrated.ts
- examples/nextjs/package.json
- examples/nextjs/yarn.lock
Jira: [LF-7886](https://lifi.atlassian.net/browse/LF-7886)
Adds the WidgetSkeleton to the NextJs example
Have looked to add this to Remix and Nuxt examples but there were a number of problems - I've added some notes to the ticket
[LF-7886]: https://lifi.atlassian.net/browse/LF-7886?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: add skeleton widget to nextjs example

- scripts/format-package-json.js
Jira: [LF-7886](https://lifi.atlassian.net/browse/LF-7886)
This allows the WidgetSkeleton to be imported without all the imports from Widget being resolved, which currently can create issues in some envirionments.
Should be able to import WidgetSkeleton using
```
import { WidgetSkeleton } from '@lifi/widget/skeleton';
```
[LF-7886]: https://lifi.atlassian.net/browse/LF-7886?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: add skeleton to the exports of the widget package

- packages/widget-playground/src/components/DrawerControls/DesignControls/FontsControl/FontsControl.tsx
Fixes [LF-8323](https://lifi.atlassian.net/browse/LF-8323)
[LF-8323]: https://lifi.atlassian.net/browse/LF-8323?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: prevent the addition of a quote breaking the widget css in playground

- packages/widget-playground-vite/package.json
- packages/widget-playground-vite/src/App.tsx
- packages/widget/src/pages/SendToWallet/BookmarksPage.tsx
- packages/widget/src/pages/SendToWallet/ConfirmAddressSheet.tsx
- packages/widget/src/pages/SendToWallet/ConnectedWalletsPage.tsx
- packages/widget/src/pages/SendToWallet/RecentWalletsPage.tsx
- packages/widget/src/pages/SendToWallet/SendToConfiguredWalletPage.tsx
- yarn.lock
Details: [LF-8589](https://lifi.atlassian.net/browse/LF-8589)
[LF-8589]: https://lifi.atlassian.net/browse/LF-8589?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: broken navigation when confirming/bookmarking address

- packages/widget/src/components/Step/StepTimer.tsx
The import for one of the common js libs we are using wasn't working properly. this is the fix
Have tested in the nextjs example and the vite widget playground
> fix: import for common js lib react-timer-hook

- packages/widget/package.json
- packages/widget/src/components/Step/StepTimer.tsx
- packages/widget/src/hooks/timer/useInterval.ts
- packages/widget/src/hooks/timer/useTimer.ts
- packages/widget/src/hooks/timer/utils.ts
- yarn.lock
JIra: [LF-9123](https://lifi.atlassian.net/browse/LF-9123)
This replaces the use of the common js package 'react-timer-hook' with an implementation that lives in the Widget codebase
[LF-9123]: https://lifi.atlassian.net/browse/LF-9123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor: use widgets own timer hook

- packages/widget-playground/src/components/DrawerControls/DesignControls/LayoutControls.tsx
- packages/widget/src/components/AppContainer.tsx
- packages/widget/src/components/TokenList/TokenList.tsx
- packages/widget/src/config/constants.ts
- packages/widget/src/pages/SelectTokenPage/useTokenListHeight.ts
- packages/widget/src/utils/elements.ts
Jira: [LF-9666](https://lifi.atlassian.net/browse/LF-9666)
- Changes the default max height to 686px
- allows the token list to fill the full height available when in `Restricted Max Height` layout mode
- Some minor improvements to the layout control, mainly so it visibly resets its to the correct values to reflect the current layout and height for widget
[LF-9666]: https://lifi.atlassian.net/browse/LF-9666?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: token list and height related improvements

- packages/widget/src/components/AppContainer.tsx
- packages/widget/src/components/Header/Header.tsx
- packages/widget/src/hooks/useHeaderHeight.ts
Jira: [LF-9991](https://lifi.atlassian.net/browse/LF-9991)
This should fix the display of the header for subvariant split in the widget
to
[LF-9991]: https://lifi.atlassian.net/browse/LF-9991?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: widget header with subvariant split

- packages/widget/src/components/PoweredBy/PoweredBy.tsx
- packages/widget/src/types/widget.ts
Details: [LF-11127](https://lifi.atlassian.net/browse/LF-11127)
[LF-11127]: https://lifi.atlassian.net/browse/LF-11127?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: improve powered by with dynamic configuration

- packages/widget/src/stores/form/FormUpdater.tsx
- packages/widget/src/stores/form/URLSearchParamsBuilder.tsx
When URL builder is enabled and user opens a page with toAddress parameter, we need to validate the address and set it up as a bookmark. This will allow direct linking to the widget with a pre-filled destination address that will be treated the same way as a manually entered and validated address.
https://github.com/user-attachments/assets/78cc5cb4-206f-4bea-adb7-dcad570b3145
> fix: validate address from URL params and bookmark it

- packages/widget/src/components/ActiveTransactions/ActiveTransactionItem.tsx
- packages/widget/src/components/Step/Step.tsx
- packages/widget/src/components/Step/StepTimer.tsx
- packages/widget/src/components/Timer/RouteTimer.tsx
- packages/widget/src/components/Timer/StepTimer.tsx
- packages/widget/src/components/Timer/TimerContent.tsx
- packages/widget/src/hooks/timer/useStopwatch.ts
- packages/widget/src/hooks/timer/utils.ts
Closes [LF-11996](https://lifi.atlassian.net/browse/LF-11996)
This PR:
- updates the widget timer from a countdown to a count up, basically replaces a timer with a stopwatch.
- tiny: hides the timer for DONE transactions
https://github.com/user-attachments/assets/9ca12725-b771-48fb-8111-a2203911aadf
[LF-11996]: https://lifi.atlassian.net/browse/LF-11996?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(timer):  counts up instead of countdown

- packages/widget/src/hooks/useRoutes.ts
- packages/widget/src/hooks/useSettingMonitor.ts
- packages/widget/src/i18n/en.json
- packages/widget/src/pages/SettingsPage/SlippageSettings/SlippageSettings.tsx
- packages/widget/src/stores/settings/useSettingsStore.ts
- packages/widget/src/types/widget.ts
closes [LF-11038](https://lifi.atlassian.net/browse/LF-11038)
This PR:
- adds an auto slippage as the default slippage with a value of `undefined`
- add a warning for when a user sets slippage to `< 0.1`
[LF-11038]: https://lifi.atlassian.net/browse/LF-11038?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: widget auto slippage mode

- packages/widget/src/components/Timer/RouteTimer.tsx
- packages/widget/src/components/Timer/StepTimer.tsx
- packages/widget/src/i18n/en.json
- packages/widget/src/utils/timer.ts
Closes [LF-12067](https://lifi.atlassian.net/browse/LF-12607)
Closes [LF-12616](https://lifi.atlassian.net/browse/LF-12616)
This PR:
- fixes the timer bug where only display the minutes and seconds parts of the timer, now we display days, hours, minutes and seconds
- Removes the timer tool tip text to reflect the change from a count up timer to countdown timer
[LF-12067]: https://lifi.atlassian.net/browse/LF-12067?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LF-12616]: https://lifi.atlassian.net/browse/LF-12616?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(timers): display hours and days section of timers, and update copy

- packages/widget/src/pages/TransactionPage/StatusBottomSheet.tsx
- packages/widget/src/types/widget.ts
https://lifi.atlassian.net/browse/LF-13299
_It is used to re-enable the _vcComponent on the feeConfig to pass in custom React components to be shown after a transaction has been executed, as part of the drawer_
> fix: enable _vcComponent

- packages/widget/src/components/SelectTokenButton/SelectTokenButton.tsx
- packages/widget/src/pages/SelectTokenPage/SelectTokenPage.tsx
- packages/widget/src/types/widget.ts
Some integrations need to have a swap-only widget experience, so we added an option to hide the chain selection UI.
> feat: add option to hide chain selection

- package.json
- packages/widget/package.json
- packages/widget/src/config/version.ts
- packages/widget/src/hooks/useToAddressRequirements.ts
We need to have hide some elements that check for required address for Jumper deposit flow.
> fix: account for hidden UI elements in required address logic

- packages/widget-playground/src/components/DrawerControls/DesignControls/VariantControl.tsx
- packages/widget/src/App.tsx
- packages/widget/src/components/AppContainer.tsx
https://lifi.atlassian.net/browse/LF-13825
_`maxHeight` is determined differently for drawer subvariant, and that condition for drawer was missing for `height` in `.full-page-container` (which corresponds to general `maxHeight`)_ 
_Observe the list in the drawer takes the whole available height._  
https://github.com/user-attachments/assets/a2c6c114-c462-4072-9c3a-c8c7da18c324
> fix: height of virtualized list in drawer

- packages/widget/src/utils/timer.ts
https://lifi.atlassian.net/browse/LF-13810
This a [fixed bug with webkit](https://github.com/WebKit/WebKit/pull/38357). 
It was recently fixed in [a Safari update](https://developer.apple.com/documentation/safari-release-notes/safari-18_4-release-notes#JavaScript), but all users have not updated yet.
So, I went with a simple fix of just removing the invalid string if it appears.
> fix(widget): hour display bug on safari

- packages/widget-playground/src/components/DrawerControls/DesignControls/VariantControl.tsx
https://lifi.atlassian.net/browse/LF-13924
_The problem is that Drawer's Default Layout has height: 100%, whereas Wide's Default layout is supposed to have height: undefined. When switching between variants, the height was not reset. Now it is._  
https://github.com/user-attachments/assets/ae5f8b39-f2e8-4910-bb4a-d9f99bbfc48b
> fix: broken height when switching from drawer variant

- packages/wallet-management/src/syncWagmiConfig.ts
- packages/wallet-management/src/useSyncWagmiConfig.ts
- packages/widget/src/providers/WalletProvider/EVMBaseProvider.tsx
https://lifi.atlassian.net/browse/LF-13928
_The original problem: Metamask SDK (triggered on onboarding, when Metamask wallet is not installed) fails to load, since Wagmi's connect() receives SUI's chain id (which is > max integer) via its config (and this is uncaught exception during casting). Wagmi works neither with SUI nor with Bitcoin, they are not supposed to be passed to Wagmi's config (useAvailableChains, etc.).
> fix: do not pass non-evm chains to wagmi

- packages/widget/src/components/ActiveTransactions/ActiveTransactions.style.ts
- packages/widget/src/components/ActiveTransactions/ActiveTransactions.tsx
https://lifi.atlassian.net/browse/LF-13926
(transaction route data was mocked before passing to `ActiveTransactionItem`, that's why looks a bit unrealistic. please see the margins, paddings, etc. of the button)
https://github.com/user-attachments/assets/1968be58-05df-41eb-b40d-ea7db9300c80
> fix: adjust show all transactions button styles

- README.md
_@mysten/dapp-kit is a peer dependency, and it should be installed by widget's users on their own_
> docs: add Sui dependency to README

- packages/widget/src/components/Step/CircularProgress.style.tsx
- packages/widget/src/pages/TransactionPage/StatusBottomSheet.style.tsx
During the migration to MUI vars we left some components not migrated.
> fix: adjust themed status color for processes and bottom sheet

- packages/widget/src/hooks/useTokenSearch.ts
- packages/widget/src/hooks/useTokens.ts
- packages/widget/src/utils/item.ts
If `allow` list of tokens does not include tokens of chainId=X, all the tokens on chain with chainId=X should be allowed. The same applied to deny. Filtering by chainId is currently missing - the current filter considers only rules for specified chains and filters out the rest. 
This fix filters config by chains before allowing allow-deny rules.
> fix: allow-deny - do not filter out tokens from unspecified chains

- packages/widget/src/components/TokenList/TokenList.tsx
- packages/widget/src/hooks/useTokenBalances.ts
- packages/widget/src/hooks/useTokens.ts
**Problem:** Using `formType` and `tokens.length` as cache keys for `token-balances` endpoint causes the balances to be refetched every time we navigate to from or to list, even when `tokens` are the same. At the same time, if we remove `formType` from cache keys and leave only `tokens.length`, when the from and to lists of tokens are different on the same chain (e.g. because of from-to allow-deny config), the token balances are not updated. Therefore, we need a better way to define whether the tokens list changed to refetch balances.
This PR moves `formType`-based check after fetching balances to exclude `formType` as a cache key
> fix: use tokens hash as cache key

- packages/widget/src/components/TokenList/TokenDetailsSheet.tsx
Currently, when token details drawer closes, the state gets cleared immediately, meaning that on closing transition there can be noticed an empty state. This PR removes clearing the state.
Before:
https://github.com/user-attachments/assets/7655bf82-fdcc-4f90-990d-21e6ac4b488a
After:
https://github.com/user-attachments/assets/490c3638-74af-4976-ad5c-8e757e959ca2
> fix: delay clearing token details not to have empty state on transition

- packages/widget/src/components/Step/StepProcess.tsx
The tx link will come from the SDK now, so we should not create it from tx hash in the widget anymore.
> fix: update transaction link handling

- packages/wallet-management/package.json
- packages/widget-playground/package.json
- packages/widget/package.json
- pnpm-lock.yaml
The PR tests the latest sdk release.
https://github.com/lifinance/sdk/releases/tag/v3.9.0-beta.0
closes https://lifi.atlassian.net/browse/LF-12980
closes https://lifi.atlassian.net/browse/LF-3239
https://github.com/lifinance/sdk/pull/292
-
https://github.com/user-attachments/assets/6d2ba31b-6aa7-452d-8555-df59b4f19988
https://github.com/user-attachments/assets/60bd9d3b-2ba3-4ebf-8c7d-a023862c9afa
- You can test with domain `lisa.x`
- You can find more domains [here](https://ud.me/lisa.x), 
- Click the other profiles section to see other profile names you can test with
- Check if the resolved address matches the address on the profile
- Make sure you switch your active wallet to the taproot wallet. (Not supported by all bitcoin wallets)
- Wallets that support PSBT signing with taproot …
> feat: add taproot wallets, and UNS support 

- examples/zustand-widget-config/src/store/createWidgetConfigStore.ts
- packages/widget-playground/src/store/editTools/createEditToolsStore.ts
- packages/widget-playground/src/store/widgetConfig/createWidgetConfigStore.ts
- packages/widget/src/stores/bookmarks/createBookmarkStore.ts
- packages/widget/src/stores/chains/createChainOrderStore.ts
- packages/widget/src/stores/chains/useChainOrder.ts
- packages/widget/src/stores/form/createFormStore.ts
- packages/widget/src/stores/header/useHeaderStore.tsx
- packages/widget/src/stores/routes/createRouteExecutionStore.ts
- packages/widget/src/stores/settings/useSendToWalletStore.ts
- packages/widget/src/stores/settings/useSplitSubvariantStore.tsx
Updated outdated zustand store setups where we use `createWithEqualityFn` function with `Object.is` equality function, since this is the same default as a standard `create` function.
Added memoization to `useChainOrder` as it triggered infinite loop with the state changes.
(settingsStore is updated in https://github.com/lifinance/widget/pull/545, skipped not to case merge conflicts)
> refactor: use zustand create instead of createWithEqualityFn

- packages/widget/src/hooks/useTokenBalances.ts
- packages/widget/src/stores/chains/ChainOrderStore.tsx
- packages/widget/src/utils/tokenList.ts
https://lifi.atlassian.net/browse/LF-15978
Fast way to reproduce the issue with switching isAllNetworks (initially selected chain was Arbitrum, then it became All networks):
https://github.com/user-attachments/assets/05e89f2a-a5ce-4c67-9060-a4bcbcf81a5c
For switching isAllNetworks:
https://github.com/user-attachments/assets/04d80496-cd70-45ff-9586-244862f431ca
> fix: search results for chains with categories
