packages/widget/src/components/ChainSelect/useChainSelect.ts, packages/widget/src/hooks/useRouteExecution.ts, packages/widget/src/hooks/useSwapRoutes.ts, packages/widget/src/hooks/useTokenAddressBalance.ts, packages/widget/src/hooks/useTokenBalance.ts, packages/widget/src/hooks/useTokenSearch.ts, packages/widget/src/pages/SettingsPage/EnabledToolsButton.tsx
Related [LF-2328](https://lifi.atlassian.net/browse/LF-2328)
[LF-2328]: https://lifi.atlassian.net/browse/LF-2328?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: update local tokens cache to keep priceUSD in sync

packages/wallet-management/src/types/index.ts, packages/wallet-management/src/walletIcons/exodus.svg, packages/wallet-management/src/walletIcons/index.ts, packages/wallet-management/src/wallets.ts
Adding Exodus wallet to wallet management
=> fix: adding exodus wallet to wallet-management

packages/widget-playground/src/components/WidgetEvents.tsx, packages/widget/src/pages/TransactionDetailsPage/ContactSupportButton.tsx, packages/widget/src/pages/TransactionDetailsPage/TransactionDetailsPage.tsx, packages/widget/src/types/events.ts
Ticket: https://lifi.atlassian.net/browse/LF-2089
=> feat: add emitter-event for contact support button

packages/widget/src/i18n/en.json
Ticket: https://lifi.atlassian.net/browse/LF-3431
=> chore: update info message for emptyTokenList

packages/wallet-management/src/wallets.ts
Ticket: https://lifi.atlassian.net/browse/LF-4876
=> chore: update Bitget Wallet name

packages/wallet-management/src/types/index.ts, packages/wallet-management/src/walletIcons/index.ts, packages/wallet-management/src/walletIcons/safepal.svg, packages/wallet-management/src/wallets.ts
jira:https://lifi.atlassian.net/jira/software/c/projects/LF/boards/15?selectedIssue=LF-5227
=> feat: SafePal wallet added

packages/widget-playground/src/config.ts, packages/widget/src/components/ChainSelect/ChainSelect.tsx, packages/widget/src/components/ChainSelect/useChainSelect.ts, packages/widget/src/components/TokenList/TokenList.tsx, packages/widget/src/components/TokenList/types.ts, packages/widget/src/components/TokenList/useTokenSelect.ts, packages/widget/src/hooks/useChains.ts, packages/widget/src/hooks/useDebouncedWatch.ts, packages/widget/src/hooks/useGasRecommendation.ts, packages/widget/src/hooks/useGasRefuel.ts, packages/widget/src/hooks/useRoutes.ts, packages/widget/src/pages/SettingsPage/SlippageSettings/SlippageSettings.style.tsx, packages/widget/src/pages/SettingsPage/SlippageSettings/SlippageSettings.tsx, packages/widget/src/providers/WidgetProvider/utils.ts, packages/widget/src/stores/chains/ChainOrderStore.tsx, packages/widget/src/stores/chains/createChainOrderStore.ts, packages/widget/src/stores/chains/types.ts, packages/widget/src/stores/chains/useChainOrder.ts, packages/widget/src/stores/form/FormStore.tsx, packages/widget/src/stores/form/URLSearchParamsBuilder.tsx, packages/widget/src/stores/form/createFormStore.ts, packages/widget/src/stores/form/types.ts, packages/widget/src/stores/form/useFieldActions.ts, packages/widget/src/stores/form/useFieldValues.ts, packages/widget/src/stores/form/useValidationActions.ts, packages/widget/src/stores/settings/useSettingsStore.ts, packages/widget/src/types/widget.ts
[LF-6153](https://lifi.atlassian.net/browse/LF-6153)
[LF-6153]: https://lifi.atlassian.net/browse/LF-6153?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: allow different chain configuration for from and to sides of the transfer

packages/widget/src/components/Header/WalletMenu.tsx
Just removing the .js extension from a couple of imports
=> fix: import paths

packages/widget/src/components/Routes/RoutesExpanded.tsx
=> fix: expandable variant is not shown with a deep route tree

packages/widget/src/components/AppContainer.tsx, packages/widget/src/components/Card/CardHeader.tsx, packages/widget/src/components/Card/CardTitle.tsx, packages/widget/src/components/ChainSelect/useChainSelect.ts, packages/widget/src/components/SelectTokenButton/SelectTokenButton.tsx, packages/widget/src/components/SendToWallet/SendToWallet.style.tsx, packages/widget/src/components/SendToWallet/SendToWalletButton.tsx, packages/widget/src/components/TokenList/useTokenSelect.ts, packages/widget/src/hooks/useToAddressReset.ts, packages/widget/src/pages/MainPage/MainPage.tsx, packages/widget/src/stores/form/useFieldController.ts
=> feat: add destination address clear button

packages/widget-playground-vite/public/manifest.json
Ensuring the manifest json is well formatted
=> fix: mainfest json

packages/widget/src/components/Routes/RoutesExpanded.tsx, packages/widget/src/types/events.ts
Ticket: https://lifi.atlassian.net/browse/LF-7193
=> feat: add widget-event on widget expansion

packages/widget-playground/src/components/DrawerControls/DesignControls/VariantControl.tsx, packages/widget-playground/src/defaultWidgetConfig.ts, packages/widget-playground/src/store/widgetConfig/utils/getWhitelistedConfig.test.ts, packages/widget/src/AppDefault.tsx, packages/widget/src/hooks/useWideVariant.ts, packages/widget/src/pages/MainPage/MainPage.tsx, packages/widget/src/types/widget.ts
Jira [LF-7287](https://lifi.atlassian.net/browse/LF-7287)
We want to change the variant names of the widget as referred to from the config to be 
default → compact
epandable → wide
[LF-7287]: https://lifi.atlassian.net/browse/LF-7287?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat!: change the variant naming

packages/widget-playground/src/store/widgetConfig/createWidgetConfigStore.ts, packages/widget-playground/src/store/widgetConfig/utils/cloneStructuredConfig.ts, packages/widget-playground/src/store/widgetConfig/utils/rehydrateFunctions.test.ts, packages/widget-playground/src/store/widgetConfig/utils/rehydrateFunctions.ts, packages/widget-playground/src/store/widgetConfig/utils/substituteFunctions.test.ts, packages/widget-playground/src/store/widgetConfig/utils/substituteFunctions.ts, packages/widget-playground/src/store/widgetConfig/utils/types.ts
Jira: [LF-7324](https://lifi.atlassian.net/browse/LF-7324)
This provides more generic shallow copying of functions in the WidgetConfig and should make some changes to the widget much easier in future
[LF-7324]: https://lifi.atlassian.net/browse/LF-7324?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: more generic handling of functions in cloning config

packages/widget/src/components/TokenList/TokenList.tsx, packages/widget/src/components/TokenList/VirtualizedTokenList.tsx, packages/widget/src/components/TokenList/utils.ts
- The exact match is shown first
- Tokens with logos have a priority
=> feat: improve sorting while searching for tokens

packages/widget/src/pages/TransactionPage/StatusBottomSheet.tsx
Fixes the height of the status bottom sheet in the same way we do for value loss and exchange rate bottom sheets. Can be reproduced on playground/jumper when swapping natives (the tokens that don't require approval process).
Before:
After:
=> fix: use correct height for status bottom sheet

packages/widget/src/hooks/useTransactionHistory.ts
Fixed timestamp parameters for api call
=> fix: round timestamps

packages/widget/src/components/Card/CardLabel.tsx, packages/widget/src/utils/colors.ts
=> fix: blend label color correctly

packages/wallet-management/package.json, packages/wallet-management/src/wallets.ts, yarn.lock
WalletConnect modal z-index was not changing to intended 3000 value
=> fix: adjust z-index key for walletConnect modal

packages/widget/src/components/ChainSelect/ChainSelect.tsx, packages/widget/src/stores/chains/createChainOrderStore.ts
[LF-8144](https://lifi.atlassian.net/browse/LF-8144)
[LF-8144]: https://lifi.atlassian.net/browse/LF-8144?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: chain can't be selected if it is tenth on the list

packages/widget/src/components/Routes/RoutesExpanded.tsx, packages/widget/src/hooks/useRoutes.ts, packages/widget/src/types/events.ts
Ticket: https://lifi.atlassian.net/browse/LF-8355
=> feat: add onRoutesAvailable widget-event

packages/widget-playground/src/store/editTools/createEditToolsStore.ts, packages/widget-playground/src/store/widgetConfig/createWidgetConfigStore.ts
Jira: [LF-8575](https://lifi.atlassian.net/browse/LF-8575)
This should make sure the localstorage keys are presented correctly
[LF-8575]: https://lifi.atlassian.net/browse/LF-8575?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: remove the quote from local storage keys

packages/widget-embedded/src/index.tsx, packages/widget-playground/src/defaultWidgetConfig.ts, packages/widget/src/hooks/useAvailableChains.ts, packages/widget/src/hooks/useGasRecommendation.ts, packages/widget/src/hooks/useTools.ts, packages/widget/src/providers/WalletProvider/EVMBaseProvider.tsx
[LF-8657](https://lifi.atlassian.net/browse/LF-8657)
[LF-8657]: https://lifi.atlassian.net/browse/LF-8657?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: make chains, bridges and exchanges config options reactive

packages/widget/src/i18n/en.json
[LF-8971](https://lifi.atlassian.net/browse/LF-8971)
[LF-4617](https://lifi.atlassian.net/browse/LF-4617)
[LF-8971]: https://lifi.atlassian.net/browse/LF-8971?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LF-4617]: https://lifi.atlassian.net/browse/LF-4617?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: adjust partial transfer message

packages/widget/src/components/TransactionDetails.tsx, packages/widget/src/utils/converters.ts
=> feat: add price impact to transaction details

packages/wallet-management/src/syncWagmiConfig.ts, packages/wallet-management/src/useSyncWagmiConfig.ts, packages/wallet-management/src/utils/convertExtendedChain.ts
[LF-9278](https://lifi.atlassian.net/browse/LF-9278)
[LF-9278]: https://lifi.atlassian.net/browse/LF-9278?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: allow syncing with mixed chains

packages/widget/src/components/ActiveTransactions/ActiveTransactionItem.tsx, packages/widget/src/components/Card/CardIconButton.tsx, packages/widget/src/components/FeeBreakdownTooltip.tsx, packages/widget/src/components/IconTypography.ts, packages/widget/src/components/RouteCard/RouteCardEssentials.tsx, packages/widget/src/components/Step/DestinationWalletAddress.tsx, packages/widget/src/components/Step/Step.tsx, packages/widget/src/components/Step/StepProcess.style.tsx, packages/widget/src/components/Step/StepProcess.tsx, packages/widget/src/components/Step/StepTimer.tsx, packages/widget/src/components/StepActions/StepActions.style.tsx, packages/widget/src/components/TransactionDetails.tsx, packages/widget/src/hooks/timer/useTimer.ts, packages/widget/src/i18n/en.json, packages/widget/src/pages/TransactionDetailsPage/TransactionDetailsPage.tsx, packages/widget/src/pages/TransactionPage/TokenValueBottomSheet.tsx, packages/widget/src/pages/TransactionPage/TransactionPage.tsx, packages/widget/src/pages/TransactionPage/utils.ts, packages/widget/src/stores/routes/types.ts, packages/widget/src/types/events.ts, packages/widget/src/utils/converters.ts, packages/widget/src/utils/fees.ts
Details: [LF-9292](https://lifi.atlassian.net/browse/LF-9292)
[LF-9292]: https://lifi.atlassian.net/browse/LF-9292?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: improve the display of estimated duration and fees

packages/widget/src/components/StepActions/StepActions.tsx, packages/widget/src/components/StepActions/types.ts, packages/widget/src/components/TransactionDetails.tsx, packages/widget/src/i18n/en.json, packages/widget/src/types/widget.ts
Details: [LF-9194](https://lifi.atlassian.net/browse/LF-9194)
[LF-9194]: https://lifi.atlassian.net/browse/LF-9194?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add option for fee tool with improved fee collection display

packages/widget/src/components/ChainSelect/useChainSelect.ts, packages/widget/src/components/TokenList/useTokenSelect.ts
[LF-9559](https://lifi.atlassian.net/browse/LF-9559)
[LF-9559]: https://lifi.atlassian.net/browse/LF-9559?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: avoid from amount/token reset if they are disabled

package.json, packages/widget-embedded/package.json, packages/widget-playground-next/package.json, packages/widget-playground-vite/package.json, packages/widget-playground/package.json, packages/widget/package.json, packages/widget/src/components/StepActions/StepActions.tsx, packages/widget/src/components/StepActions/types.ts, packages/widget/src/components/TransactionDetails.tsx, packages/widget/src/config/version.ts, packages/widget/src/hooks/useRoutes.ts, packages/widget/src/providers/WidgetProvider/WidgetProvider.tsx, packages/widget/src/stores/routes/createRouteExecutionStore.ts, packages/widget/src/types/widget.ts, yarn.lock
Part of the [LF-9194](https://lifi.atlassian.net/browse/LF-9194)
[LF-9194]: https://lifi.atlassian.net/browse/LF-9194?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: improved fee configuration

packages/widget/src/components/Token/Token.tsx, packages/widget/src/components/TransactionDetails.tsx, packages/widget/src/i18n/en.json, packages/widget/src/providers/I18nProvider/I18nProvider.tsx, packages/widget/src/providers/I18nProvider/percentFormatter.ts
Details: [LF-9696](https://lifi.atlassian.net/browse/LF-9696)
[LF-9696]: https://lifi.atlassian.net/browse/LF-9696?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: add percent formatter to improve display of price impact

packages/widget-playground/src/defaultWidgetConfig.ts, packages/widget-playground/src/store/widgetConfig/utils/getConfigOutput.ts, packages/widget/src/components/Header/WalletMenu.tsx, packages/widget/src/components/Step/Step.tsx, packages/widget/src/components/Step/StepProcess.tsx, packages/widget/src/components/TokenList/TokenListItem.tsx, packages/widget/src/hooks/useExplorer.ts, packages/widget/src/hooks/useProcessMessage.ts, packages/widget/src/pages/SendToWallet/BookmarksPage.tsx, packages/widget/src/pages/SendToWallet/ConnectedWalletsPage.tsx, packages/widget/src/pages/SendToWallet/RecentWalletsPage.tsx, packages/widget/src/pages/SendToWallet/SendToConfiguredWalletPage.tsx, packages/widget/src/pages/TransactionDetailsPage/TransferIdCard.tsx, packages/widget/src/types/widget.ts
JIra: [LF-9882](https://lifi.atlassian.net/browse/LF-9882)
Allows configuration of explorer urls in the Widget
[LF-9882]: https://lifi.atlassian.net/browse/LF-9882?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: allow configuration of explorer links

packages/widget-playground/src/defaultWidgetConfig.ts, packages/widget/src/components/Card/CardLabel.tsx, packages/widget/src/components/RouteCard/RouteCard.tsx, packages/widget/src/components/RouteCard/getMatchingLabels.ts, packages/widget/src/types/widget.ts
Details: [LF-11548](https://lifi.atlassian.net/browse/LF-11548)
[LF-11548]: https://lifi.atlassian.net/browse/LF-11548?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add configurable route labels/badges

packages/widget/src/components/RouteCard/RouteCard.tsx, packages/widget/src/components/Token/Token.tsx, packages/widget/src/types/widget.ts
[LF-12707](https://lifi.atlassian.net/browse/LF-12707)
[LF-12707]: https://lifi.atlassian.net/browse/LF-12707?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add RouteTokenDescription hidden option

packages/widget/src/pages/TransactionPage/StartTransactionButton.tsx
[LF-13342](https://lifi.atlassian.net/browse/LF-13342)
[LF-13342]: https://lifi.atlassian.net/browse/LF-13342?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: allow to create txs without enough gas

packages/widget-playground/src/defaultWidgetConfig.ts, packages/widget/src/components/BaseTransactionButton/BaseTransactionButton.tsx, packages/widget/src/components/BaseTransactionButton/types.ts, packages/widget/src/components/Messages/MissingRouteRequiredAccountMessage.tsx, packages/widget/src/components/Messages/WarningMessages.tsx, packages/widget/src/components/Messages/useMessageQueue.ts, packages/widget/src/hooks/useGasSufficiency.ts, packages/widget/src/hooks/useIsContractAddress.ts, packages/widget/src/hooks/useRouteRequiredAccountConnection.ts, packages/widget/src/hooks/useRoutes.ts, packages/widget/src/i18n/en.json, packages/widget/src/pages/MainPage/ReviewButton.tsx, packages/widget/src/pages/TransactionPage/StartTransactionButton.tsx
[LF-12713](https://lifi.atlassian.net/browse/LF-12713) 
[LF-12713]: https://lifi.atlassian.net/browse/LF-12713?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add cross-vm 2-steps tx flow

packages/widget/src/components/SelectTokenButton/SelectTokenButton.style.tsx
Before: 
https://github.com/user-attachments/assets/a8599645-f970-4c21-95f7-a3553f07bea9
After: 
https://github.com/user-attachments/assets/72fa4d27-27ae-48b6-bf7a-39592183f91c
=> fix: missing highlight on Azure theme

package.json, packages/widget/src/components/SendToWallet/SendToWalletButton.tsx
Addresses this problem: 
https://github.com/user-attachments/assets/8fe8db45-7b01-4ff1-adc6-be2e41e15093
=> fix: wallet toggle, add cache cleaning command

packages/widget/src/components/Header/Header.style.ts
Addresses comments from https://lifi.atlassian.net/browse/LF-14312?focusedCommentId=22107
=> fix: cutoff corners on full height

packages/widget/src/components/Routes/RoutesContent.tsx, packages/widget/src/components/Routes/RoutesExpanded.tsx
[LF-15070](https://lifi.atlassian.net/browse/LF-15070)
[LF-15070]: https://lifi.atlassian.net/browse/LF-15070?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: improve cache handling for fetched routes

packages/widget/src/hooks/useAccountsBalancesData.ts, packages/widget/src/hooks/useFilteredByTokenBalances.ts
https://lifi.atlassian.net/browse/LF-15368
Added allow-deny filtering on token concatenation
=> fix: respect token deny list for tokens with balances

packages/widget/src/hooks/useFilteredByTokenBalances.ts, packages/widget/src/hooks/useToken.ts, packages/widget/src/hooks/useTokenSearch.ts, packages/widget/src/utils/token.ts, packages/widget/src/utils/tokenList.ts
https://lifi.atlassian.net/browse/LF-15385
Added lower casing before comparison to all the token address-based occurrences.
=> fix: use lower case when comparing addresses
